### ISSUE TITLE
[Bug]: Weird audio snippet on Battery On

### ISSUE THREAD

**Issue by Toy203** [gpstar81/GPStar-proton-pack#390] opened 2024-10-08 17:16 UTC
### What actions were attempted?

Switching the battery on plays a sound bit before the regular Power On sound

### What actually happened?

https://youtu.be/S9-L27-sWBw
Note that yes i have a custom "power on" sound that was edited to include ALIEN sounds in it.

### What was expected?

No weird audio bits lol

### Firmware Version

5.4.0 - 1.03

### Mode in Use

Super Hero / Video Game

### Notable Hardware

Nope

### Homework Completed

- [X] I did my part!

**Comment by gpstar81** [comment] 2024-10-08 17:24
It is because your wand has not been flashed yet to the newest firmware.

**Comment by Toy203** [comment] 2024-10-08 17:26
Flashed all three and cleared  eeprom. Didn't try to plug it off and on to the pack though, let me see.

**Comment by Toy203** [comment] 2024-10-08 19:58
Flashed both pack and wand again, no luck. Might try with a "clean" sd card with just regular sounds to see if that change anything.

**Comment by DustinGrau** [comment] 2024-10-08 20:03
Well that's odd. I had on occasion heard the startup fire after battery-on, but not 100% of the time. The trailing audio on that is VERY odd though. Make sure you're fully updated with all sound effects.

**Comment by nomakewan** [comment] 2024-10-08 20:29
> Well that's odd. I had on occasion heard the startup fire after battery-on, but not 100% of the time. The trailing audio on that is VERY odd though. Make sure you're fully updated with all sound effects.

The trailing audio is their own custom POST sound effect. ;)

**Comment by Toy203** [comment] 2024-10-08 21:00
Correct, POST is edited. Tried with clean SD and just reg sounds, same behaviour.

**Comment by nomakewan** [comment] 2024-10-08 21:34
Problem identified and resolved in GPStar Audio firmware. Thank you so much for this report!

**Comment by nomakewan** [comment] 2024-10-08 21:40
Confirmed fixed in 92691f5.

**Closed by nomakewan** 2024-10-08 21:40 UTC
Labels: bug
