### ISSUE TITLE
Cyclotron lid slime mode not working 

### ISSUE THREAD

**Issue by Rizzbuster** [gpstar81/GPStar-proton-pack#333] opened 2024-07-08 13:02 UTC
Cycling lid issue. Tested all the year modes and slime mode is not working. I did get continuing fire at one point but can't pin point how it happened yet.

**Comment by Toy203** [comment] 2024-07-08 13:05
Can reproduce, no lights in the circles on Slime mode. I got 9 led pucks mounted.

**Comment by DustinGrau** [comment] 2024-07-08 13:13
From reports, one user is on the stock lights, another on Frutto, so this is not immediately related to RGB vs. standard.

**Comment by nomakewan** [comment] 2024-07-08 14:41
Found the issue. It's so stupid as to be unreal.

**Comment by nomakewan** [comment] 2024-07-08 14:49
So to fix the issues with ramp speeds not being correct if you boot the Proton Pack in Slime and then switch firing modes (or recover from overheat in slime and switch firing modes), I moved the call to the slime lights into the actual cyclotron control loops. The problem is I forgot there was a call that _skips those control loops entirely_ if we're in slime mode.

Fixed now.

**Comment by nomakewan** [comment] 2024-07-08 14:54
> Can reproduce, no lights in the circles on Slime mode. I got 9 led pucks mounted. Also, in Slime mode (AF) my power cell is still running once i turn off the pack from the ion arm or wand.

Please test the [new binary](https://github.com/gpstar81/GPStar-proton-pack/blob/v5.3.1/develop/binaries/pack/ProtonPack.hex) on your pack to see if it resolves all of these issues. If it does, awesome. If not, that lets us know to keep looking into the power cell and vibration stuff.

**Comment by Toy203** [comment] 2024-07-08 15:10
Sorry, no luck. Same behaviour as before both for cyclotron ring and power cell

**Comment by nomakewan** [comment] 2024-07-08 15:17
> Sorry, no luck. Same behaviour as before both for cyclotron ring and power cell. Should i erase eeprom and try?

Erasing EEPROM has not been necessary since 5.0.0. It will have no effect here since the issue is with code, not EEPROM settings.

I will see what else I can do to work this out.

**Comment by nomakewan** [comment] 2024-07-08 15:25
> Sorry, no luck. Same behaviour as before both for cyclotron ring and power cell. Should i erase eeprom and try?

Okay, new binary is pushed (it has the same URL as above). Please test this one.

**Comment by Toy203** [comment] 2024-07-08 15:46
Looks like both problem are fixed with this! Tried also in 84/89, no issues. Cyclotron lights up and no more power cell going after shutdown.

**Comment by nomakewan** [comment] 2024-07-08 15:46
@Rizzbuster See if everything is good on your end as well. If so, we can consider this issue Busted!

**Closed** 2024-07-08 16:37 UTC
