### ISSUE TITLE
Halloween Spectral Swap

### ISSUE THREAD

**Issue by Aces6469** [gpstar81/GPStar-proton-pack#368] opened 2024-08-25 00:25 UTC
### What would you like to add in terms of software changes?

Kinda surprised I haven't seen anyone ask it yet, but possibly an LED setting that changes the colors of the christmas mode to purple and orange for Halloween? 

### Would this request involve any specific hardware?

Frutto Powercell, 5 or 9 LED PCBs.

### Homework Completed

- [X] I did my part!

**Comment by DustinGrau** [comment] 2024-08-25 00:36
This does actually exist, it's just not exposed as an option. I started to add some other color combos as I figured people may want sports team colors or other holidays, namely Halloween. So the ability isn't far off, just not made into a user preference.

**Comment by DustinGrau** [comment] 2024-08-25 00:37
Look at https://github.com/gpstar81/GPStar-proton-pack/blob/main/source/ProtonPack/Colours.h
C_ORANGEPURPLE was intended to do just this thing

**Comment by nomakewan** [comment] 2024-08-25 00:43
Yep, it's been in the code since literally forever. We just have to figure out some way to select _which_ holiday and it'll be good to go.

If you have any suggestions on how to switch between Christmas and Halloween for the Holiday mode, we're all ears!

**Comment by Aces6469** [comment] 2024-08-25 02:37
Could use the wing button at the end of the thrower? Last I recall it does nothing in the spectral modes with all toggles up.

**Comment by nomakewan** [comment] 2024-08-25 02:39
And so the solution presents itself instantly. Gonna go ahead and assign this to myself and get it ready for 5.3.4.

**Comment by nomakewan** [comment] 2024-09-07 14:29
Holiday modes for both Christmas and Halloween are now fully implemented and will be in the 5.3.4 release. Thank you for your suggestions!

**Closed by nomakewan** 2024-09-07 14:29 UTC
Labels: enhancement
